export interface TikTokTrend {
  id: string;
  category: 'cabelo' | 'cosmeticos' | 'unhas' | 'audios';
  categoryLabel: string;
  name: string;
  hashtag: string;
  growth: string;
  views: string;
  badge: 'EXPLODINDO' | 'EM ALTA' | 'VIRAL' | 'NOVO' | 'LUXO';
  badgeColor: string;
  description: string;
  suggestedHook: string;
  videoFormat: 'Reels / TikTok' | 'Carrossel' | 'Antes & Depois' | 'Tutorial Rápido';
  soundtrackSuggestion?: string;
  tiktokUrl: string;
  creativeCenterUrl: string;
}

export const TIKTOK_BEAUTY_TRENDS: TikTokTrend[] = [
  {
    id: 'trend-1',
    category: 'cabelo',
    categoryLabel: 'Cabelos & Mechas',
    name: 'Acidificação Capilar',
    hashtag: '#acidificacaocapilar',
    growth: '+184% este mês',
    views: '38.2M visualizações',
    badge: 'EXPLODINDO',
    badgeColor: 'bg-rose-500 text-white',
    description: 'Tratamento pós-química para selar cutículas e devolver o brilho espelhado aos fios porosos.',
    suggestedHook: 'Se o seu cabelo tá poroso e sem vida, você precisa desse procedimento urgente!',
    videoFormat: 'Antes & Depois',
    soundtrackSuggestion: 'Vibes acústicas / Lo-fi clean girl aesthetic',
    tiktokUrl: 'https://www.tiktok.com/tag/acidificacaocapilar',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt?countryCode=BR',
  },
  {
    id: 'trend-2',
    category: 'cabelo',
    categoryLabel: 'Cabelos & Mechas',
    name: 'Morena Iluminada Mel Tabaco',
    hashtag: '#morenailuminada',
    growth: '+142% este mês',
    views: '94.7M visualizações',
    badge: 'LUXO',
    badgeColor: 'bg-amber-600 text-white',
    description: 'Nuances quentes elegantes para mulheres que buscam clareamento sofisticado sem descoloração extrema.',
    suggestedHook: 'O tom de morena iluminada mais pedido pelas nossas clientes neste outono ✨',
    videoFormat: 'Reels / TikTok',
    soundtrackSuggestion: 'Transição rítmica no momento do balanço do cabelo',
    tiktokUrl: 'https://www.tiktok.com/tag/morenailuminada',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt?countryCode=BR',
  },
  {
    id: 'trend-3',
    category: 'cabelo',
    categoryLabel: 'Cabelos & Mechas',
    name: 'Corte Butterfly (Camadas Suaves)',
    hashtag: '#butterflycut',
    growth: '+95% esta semana',
    views: '112.5M visualizações',
    badge: 'VIRAL',
    badgeColor: 'bg-purple-600 text-white',
    description: 'Corte em camadas volumosas que confere movimento aerado sem encurtar o comprimento dos fios.',
    suggestedHook: 'Cansada do cabelo reto e pesado? Veja como o corte em camadas muda completamente o rosto!',
    videoFormat: 'Tutorial Rápido',
    soundtrackSuggestion: 'Pop chic / batida moderna suave',
    tiktokUrl: 'https://www.tiktok.com/tag/butterflycut',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt?countryCode=BR',
  },
  {
    id: 'trend-4',
    category: 'cosmeticos',
    categoryLabel: 'Cosméticos & Tratamentos',
    name: 'Óleos Finalizadores com Proteção Térmica',
    hashtag: '#oleocapilar',
    growth: '+128% este mês',
    views: '46.1M visualizações',
    badge: 'EM ALTA',
    badgeColor: 'bg-emerald-600 text-white',
    description: 'Dicas de uso correto do óleo capilar profissional para evitar fios pesados e pontas duplas.',
    suggestedHook: 'Você provavelmente está passando o óleo reparador do jeito errado no seu cabelo...',
    videoFormat: 'Reels / TikTok',
    soundtrackSuggestion: 'Voz explicativa com trilha relaxante de fundo',
    tiktokUrl: 'https://www.tiktok.com/tag/oleocapilar',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt?countryCode=BR',
  },
  {
    id: 'trend-5',
    category: 'cosmeticos',
    categoryLabel: 'Cosméticos & Tratamentos',
    name: 'Skin Cycling & Glow Skin no Salão',
    hashtag: '#skincarebrasil',
    growth: '+115% este mês',
    views: '83.9M visualizações',
    badge: 'EXPLODINDO',
    badgeColor: 'bg-rose-500 text-white',
    description: 'Protocolos de limpeza profunda e hidratação facial com viço natural ("Clean Girl Skincare").',
    suggestedHook: 'Pele de porcelana sem maquiagem pesada: o segredo do nosso protocolo glow.',
    videoFormat: 'Carrossel',
    soundtrackSuggestion: 'Música ASMR / sons de pincel e água relaxante',
    tiktokUrl: 'https://www.tiktok.com/tag/skincarebrasil',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt?countryCode=BR',
  },
  {
    id: 'trend-6',
    category: 'cabelo',
    categoryLabel: 'Cabelos & Mechas',
    name: 'Loiro Perolado Saudável',
    hashtag: '#loiroperolado',
    growth: '+88% este mês',
    views: '62.4M visualizações',
    badge: 'LUXO',
    badgeColor: 'bg-amber-600 text-white',
    description: 'Fundo de clareamento limpo com preservação total da elasticidade do fio através de plex.',
    suggestedHook: 'Loiro claríssimo sem quebra: teste de mecha e o segredo da saúde do fio!',
    videoFormat: 'Antes & Depois',
    soundtrackSuggestion: 'Transição com efeito sonoro "whoosh"',
    tiktokUrl: 'https://www.tiktok.com/tag/loiroperolado',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt?countryCode=BR',
  },
  {
    id: 'trend-7',
    category: 'unhas',
    categoryLabel: 'Unhas & Estética',
    name: 'Unhas Glazed Donut / Clean Girl',
    hashtag: '#glazeddonutnails',
    growth: '+76% esta semana',
    views: '41.8M visualizações',
    badge: 'VIRAL',
    badgeColor: 'bg-purple-600 text-white',
    description: 'Esmaltação perolada minimalista com acabamento cromado sutil em unhas amendoadas.',
    suggestedHook: 'A esmaltação que as celebridades mais usam e que combina com qualquer look!',
    videoFormat: 'Reels / TikTok',
    soundtrackSuggestion: 'Áudio pop trending / aesthetic sound',
    tiktokUrl: 'https://www.tiktok.com/tag/glazeddonutnails',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/pt?countryCode=BR',
  },
  {
    id: 'trend-8',
    category: 'audios',
    categoryLabel: 'Áudios & Sons Virais',
    name: 'Áudio Viral: Transição "Before & After Glow"',
    hashtag: '#hairtransformation',
    growth: '+320% este mês',
    views: '240M vídeos no Brasil',
    badge: 'EXPLODINDO',
    badgeColor: 'bg-rose-500 text-white',
    description: 'Música rítmica com batida sincronizada ideal para corte no exato momento da revelação do cabelo.',
    suggestedHook: 'Comece filmando o cabelo preso e sem escova, solte no drop da música!',
    videoFormat: 'Reels / TikTok',
    soundtrackSuggestion: 'Batida acelerando com drop aos 4 segundos',
    tiktokUrl: 'https://www.tiktok.com/tag/hairtransformation',
    creativeCenterUrl: 'https://ads.tiktok.com/business/creativecenter/inspiration/popular/music/pc/pt?countryCode=BR',
  },
];
